---
- name: Create local user account on each system
  hosts: all
  become: true
  gather_facts: false

  vars:
    new_user: "AdminWGU"
    new_pass_hash: "<PASTE_$6$_HASH_HERE>"

  tasks:
    - name: Create local user account
      ansible.builtin.user:
        name: "{{ new_user }}"
        password: "{{ new_pass_hash }}"
        shell: /bin/bash
        create_home: true
        state: present