ubuntu_servers:
  hosts:
    34.220.251.116:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/student/.ssh/d417key

rhel_servers:
  hosts:
    52.37.244.21:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/student/.ssh/d417key